### PR TITLE
user can now choose path threw file explorer (save too!)

### PR DESCRIPTION
**Pull request by steliosdask**

### CODE REVIEW

**Comment by GMetaxakis** [comment]
this conflict exists as the change in `utils.py` file has happened in the branch historically before the last change in the `main` branch

this can say that probably the `testing-branch` was created before the commit b898c83826d4a6f7e1d78a8af390d2b0ec4b738 .

We can verify this if we go [here](https://github.com/steliosdask/syfak/commits/6e81ceba278d0199c747f8dae96888f8614ac481/utils.py) we see the commit history of the `utis.py` that exists in the branch `testing-branch` and we don't see the commit (b898c83826d4a6f7e1d78a8af390d2b0ec4b738) with the latest changes in the `main` branch

**Comment by GMetaxakis** [comment]
Resolving solutions,
* Rebase the branch (tricky one)
* Merge `main` to `testing-branch` and keep the last "state" of the code that you want

The `Resolve conflicts` in browser does the second solution :)

**Comment by steliosdask** [comment]
I've messed it up a lot now for sure. Need to understand better how all this work :/

**Comment by GMetaxakis** [comment]
revert commit b555382

**Comment by GMetaxakis** [comment]
or just add this
```python
        out_path = saveto + '\\' + st1 + st2 + st3 + '.xlsx'
        xlsx_file.to_excel(out_path, index=False)

```

**Pull request merged**
